<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
  <TargetFramework>net8.0</TargetFramework>
  <ImplicitUsings>enable</ImplicitUsings>
  <Nullable>enable</Nullable>
  <RootNamespace>ProductCaseArtius.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.6" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.8" />
    <PackageReference Include="PDFsharp-MigraDoc" Version="6.1.0-preview-3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProductCaseArtius.Communication\ProductCaseArtius.Communication.csproj" />
    <ProjectReference Include="..\ProductCaseArtius.Domain\ProductCaseArtius.Domain.csproj" />
    <ProjectReference Include="..\ProductCaseArtius.Exception\ProductCaseArtius.Exception.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Logo\ProfilePhoto.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
